version: '2.4'

services:
  postgres:
    container_name: db-postgres
    image: postgres:11.6
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=app_db
    command: ["postgres", "-c", "log_statement=all"]

#   mockserver:
#   image: mockserver/mockserver:mockserver-5.10.0
#   ports:
#      - 1080:1080
#    environment:
#      LOG_LEVEL: "DEBUG"
#      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
#      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
#      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
#    volumes:
#      - type: bind
#        source: ./server
#        target: /config
#  pgadmin:
#    image: dpage/pgadmin4
#    restart: always
#    depends_on:
#      - postgres
#    ports:
#      - 5050:80
#    environment:
#      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
#      PGADMIN_DEFAULT_PASSWORD: admin

#  rabbitmq:
#    container_name: lacafetalab-java_ddd_skeleton-rabbitmq
#    image: 'rabbitmq:3.7-management'
#    restart: unless-stopped
#    ports:
#      - 5672:5672
#      - 15672:15672
#    environment:
#      - RABBITMQ_DEFAULT_USER=lacafetalab
#      - RABBITMQ_DEFAULT_PASS=caf3ta

#  elasticsearch:
#    container_name: lacafetalab-java_ddd_skeleton-elasticsearch
#    image: 'elasticsearch:6.8.4'
#    restart: unless-stopped
#    ports:
#      - 9300:9300
#      - 9200:9200
#    environment:
#      - discovery.type=single-node

